name       : kdialog
version    : 21.08.1
release    : 47
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.1/src/kdialog-21.08.1.tar.xz : 24a90bdef85a9e189f080bdc6724d604f4a4d6610d33ba26862dc0525991b5d7
homepage   : https://kde.org/applications/utilities/org.kde.kdialog
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : KDialog can be used to show nice dialog boxes from shell scripts
description: |
    KDialog allows you to display dialog boxes from shell scripts. The syntax is very much inspired from the "dialog" command (which shows text mode dialogs).
optimize   : lto
builddeps  :
    - pkgconfig(x11)
    - kdbusaddons-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - ktextwidgets-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
