name       : kdialog
version    : 23.04.3
release    : 62
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.3/src/kdialog-23.04.3.tar.xz : 5def1a148f19b087adaa7eb634f45e17266d69657dec776e37593d9bdaf94a10
homepage   : https://kde.org/applications/utilities/org.kde.kdialog
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : KDialog can be used to show nice dialog boxes from shell scripts
description: |
    KDialog allows you to display dialog boxes from shell scripts. The syntax is very much inspired from the "dialog" command (which shows text mode dialogs).
optimize   : lto
builddeps  :
    - pkgconfig(x11)
    - kdbusaddons-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - ktextwidgets-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
