name       : kdialog
version    : 21.08.0
release    : 46
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.0/src/kdialog-21.08.0.tar.xz : d4af3cd41b34a4dc3f3ef23238f9791f1470ce5362c2edbf6354e6ce1b0471de
homepage   : https://kde.org/applications/utilities/org.kde.kdialog
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : KDialog can be used to show nice dialog boxes from shell scripts
description: |
    KDialog allows you to display dialog boxes from shell scripts. The syntax is very much inspired from the "dialog" command (which shows text mode dialogs).
optimize   : lto
builddeps  :
    - pkgconfig(x11)
    - kdbusaddons-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - ktextwidgets-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
