name       : kdialog
version    : 18.04.2
release    : 6
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.2/src/kdialog-18.04.2.tar.xz : 76e68f5b2dedf05572598bc4528f22f1cdc288a17d8e81e7ab0b9ecb54b3db2d
license    : GPL-2.0
component  : desktop.kde
optimize   : lto
summary    : KDialog can be used to show nice dialog boxes from shell scripts
description: |
    KDialog allows you to display dialog boxes from shell scripts. The syntax is very much inspired from the "dialog" command (which shows text mode dialogs).
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kdbusaddons-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - ktextwidgets-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
