name       : kdialog
version    : 19.12.2
release    : 26
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.2/src/kdialog-19.12.2.tar.xz : 974bd61018ce5883a2c4e3cdc0dba891f2018dc2bf6e668b02afc2560b69b5ff
homepage   : https://kde.org/applications/utilities/org.kde.kdialog
license    : GPL-2.0-or-later
component  : desktop.kde
optimize   : lto
summary    : KDialog can be used to show nice dialog boxes from shell scripts
description: |
    KDialog allows you to display dialog boxes from shell scripts. The syntax is very much inspired from the "dialog" command (which shows text mode dialogs).
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kdbusaddons-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - ktextwidgets-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
