name       : kdialog
version    : 19.08.3
release    : 23
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.3/src/kdialog-19.08.3.tar.xz : 2fa2e07fb9975e2e32e26a2a17350ef253b93471017e5945a2df0fef2eeba787
license    : GPL-2.0-or-later
component  : desktop.kde
optimize   : lto
summary    : KDialog can be used to show nice dialog boxes from shell scripts
description: |
    KDialog allows you to display dialog boxes from shell scripts. The syntax is very much inspired from the "dialog" command (which shows text mode dialogs).
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kdbusaddons-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - ktextwidgets-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
