name       : kdialog
version    : 18.04.3
release    : 7
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.3/src/kdialog-18.04.3.tar.xz : ec08c9d8f8a474a157cc0ae0f405ef563df671af62cf6d952a9597e6c5b91d9d
license    : GPL-2.0
component  : desktop.kde
optimize   : lto
summary    : KDialog can be used to show nice dialog boxes from shell scripts
description: |
    KDialog allows you to display dialog boxes from shell scripts. The syntax is very much inspired from the "dialog" command (which shows text mode dialogs).
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kdbusaddons-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - ktextwidgets-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
